version: '3.4'
  
services:
    test: 
        build:
            context: .
            target: ospos_test
        depends_on: 
          - postgres
        container_name: ospos_test
        environment:
          - CI_ENV=testing
          - ENCRYPTION_KEY=
          - POSTGRES_HOST_NAME=postgres
          - POSTGRES_DB_NAME=ospos
          - POSTGRES_USERNAME=admin
          - POSTGRES_PASSWORD=pointofsale
        command: ["/bin/wait-for-it.sh", "postgres:5432", "--", "/app/vendor/phpunit/phpunit/phpunit"]
        ports:
          - "80:80"

    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        volumes:
          - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
          - ./database/constraints.sql:/docker-entrypoint-initdb.d/constraints.sql
        environment:
          - POSTGRES_ROOT_PASSWORD=Chengecha@26!
          - POSTGRES_DB=ospos
          - POSTGRES_USER=felix
          - POSTGRES_PASSWORD=Chengecha@26!
