-- PostgreSQL conversion

-- Add custom fields to items table
ALTER TABLE ospos_items 
ADD COLUMN IF NOT EXISTS custom1 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom2 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom3 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom4 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom5 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom6 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom7 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom8 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom9 VARCHAR(25),
ADD COLUMN IF NOT EXISTS custom10 VARCHAR(25);


ALTER TABLE ospos_giftcards 
ADD COLUMN IF NOT EXISTS person_id INTEGER;
